########################################**
#File: makefile
#Description: A file that uses merge sort
#recursivly and iteratively and records
#the time it takes to run each function.
##########################################

CXX = g++
CXXFLAGS = -std=c++0x
CXXFLAGS += -Wall
CXXFLAGS += -pedantic-errors
CXXFLAGS += -g

SRC = Main.cpp
 
PROG = LabH

default:
	${CXX} ${SRC} -o ${PROG}

clean:
	rm -f ${PROG} *.o *~
