###########################################
# File: makefile                          #
# Description: A circular doubly linked   #
# char data storing program               #
###########################################

CXX = g++
CXXFLAGS = -std=c++0x
CXXFLAGS += -Wall
CXXFLAGS += -pedantic-errors
CXXFLAGS += -g

SRCS = Main.cpp

PROG = LabE

default:
	${CXX} ${SRCS} -o ${PROG}

clean:
	rm -f ${PROG} *.o *~
